enableGlow: true
SURVIVAL_GAMES:
  PregameTime: 30
  # total game time, excluding deathmatch
  GameTime: 420
  #time at the start of the game before you can PVP
  GracePeriod: 45
  #time before chests will be restocked
  RestockTime: 90
  # countdown from when there are 2 teams left
  PreDeathmatchTime: 20
  #time while players are in spawn boxes to countdown deathmatch
  DeathmatchPrepTime: 15
  DeathmatchTime: 120
  #time countdown after the game ends
  GameEndTime: 20

  #points given for a kill
  killPoints: 100
  #points given to the winning team (divided among players)
  winPoints: 600
  #points given to alive players when someone else dies
  survivalPoints: 20

  chest:
    # number of items to put in each chest
    min: 3
    max: 11
    # items to put in the chests:
    # POTION, [num], TYPE, time, amplifier
    # ENCHANTED_BOOK, [num], ENCHANT, level
    # ITEM, [num], ENCHANT, [level], ENCHANT, [level], ...

    #unimplemented
    #l1Chance: 5
    #l2Chance: 4
    #l3Chance: 3
    #l4Chance: 2
    #l5Chance: 1

    #chances should a percent value /100
    #they don't all HAVE to add up to 100

    #dropoff is the amount decreased
    #chances should a percent value /100
    #they don't all HAVE to add up to 100

    #dropoff is the amount decreased
    WEAPONS:
      chance: 40
      dropoff: 25
      level1:
        - leather_helmet
      level2:
        - string,2
      level3:
        - chainmail_chestplate
      level4:
        - iron_leggings
      level5:
        - iron_chestplate

    ARMOR:
      chance: 40
      dropoff: 25
      level1:
        - leather_helmet
      level2:
        - string,2
      level3:
        - chainmail_chestplate
      level4:
        - iron_leggings
      level5:
        - iron_chestplate

    FOOD:
      chance: 40
      dropoff: 25
      level1:
        - leather_helmet
      level2:
        - string,2
      level3:
        - chainmail_chestplate
      level4:
        - iron_leggings
      level5:
        - iron_chestplate

    SPECIAL:
      chance: 40
      dropoff: 25
      level1:
        - leather_helmet
      level2:
        - string,2
      level3:
        - chainmail_chestplate
      level4:
        - iron_leggings
      level5:
        - iron_chestplate

SKYWARS:
  PregameTime: 15
  # total game time
  GameTime: 720
  #time before chests will be restocked
  RestockTime: 360
  GameEndTime: 10

  #points given for a kill
  killPoints: 100
  #points given to the winning team (divided among players)
  winPoints: 600
  #points given to alive players when someone else dies
  survivalPoints: 20

  # number of items to put in each chest
  chest:
    min: 13
    max: 19
    #unimplemented
    #l1Chance: 5
    #l2Chance: 4
    #l3Chance: 3
    #l4Chance: 2
    #l5Chance: 1

    #chances should a percent value /100
    #they don't all HAVE to add up to 100

    #dropoff is the amount decreased
    WEAPONS:
      chance: 40
      dropoff: 25
      level1:
        - leather_helmet
      level2:
        - string,2
      level3:
        - chainmail_chestplate
      level4:
        - iron_leggings
      level5:
        - iron_chestplate

    ARMOR:
      chance: 40
      dropoff: 25
      level1:
        - leather_helmet
      level2:
        - string,2
      level3:
        - chainmail_chestplate
      level4:
        - iron_leggings
      level5:
        - iron_chestplate

    BLOCKS:
      chance: 40
      dropoff: 25
      level1:
        - leather_helmet
      level2:
        - string,2
      level3:
        - chainmail_chestplate
      level4:
        - iron_leggings
      level5:
        - iron_chestplate

    FOOD:
      chance: 40
      dropoff: 25
      level1:
        - leather_helmet
      level2:
        - string,2
      level3:
        - chainmail_chestplate
      level4:
        - iron_leggings
      level5:
        - iron_chestplate

    TOOLS:
      chance: 40
      dropoff: 25
      level1:
        - leather_helmet
      level2:
        - string,2
      level3:
        - chainmail_chestplate
      level4:
        - iron_leggings
      level5:
        - iron_chestplate

    SPECIAL:
      chance: 40
      dropoff: 25
      level1:
        - leather_helmet
      level2:
        - string,2
      level3:
        - chainmail_chestplate
      level4:
        - iron_leggings
      level5:
        - iron_chestplate